### ISSUE TITLE
[config file] specify <files|directories|globs>

### ISSUE THREAD

**Issue by naseemkullah** [igorshubovych/markdownlint-cli#159]
Is there a way today to specify the target <files|directories|globs> in the config file?

**Comment by DavidAnson** [comment]
No. `.markdownlint.json/yaml` is exclusively for configuring rules because it is shared by the CLI, VS Code extension, etc..

There is another CLI, https://github.com/DavidAnson/markdownlint-cli2, that additionally supports a configuration file which can include ALL supported options EXCEPT the list of files to scan. That's done for performance reasons, more here: https://dlaa.me/blog/post/markdownlintcli2

I could maybe add a simple file list to the root configuration in that tool if that works for you?

**Comment by naseemkullah** [comment]
Thanks for confirming that this is not possible today!

re cli2: Is that to say there would be a  `.markdownlint-cli2.json/yaml` with the rule configuration, ignored files and the potential included file list (new feature)  which would replace the traditional `.markdownlint.json/yaml` + `.makrdownlintignore` and  <files|directories|globs> argument?

**Comment by DavidAnson** [comment]
Right. You can confirm everything today except for the file list.

**Comment by DavidAnson** [comment]
The next release of `markdownlint-cli2` will support a `globs` parameter in `.markdownlint.json/yaml/js`: https://github.com/DavidAnson/markdownlint-cli2/commit/70661528f080c2a1b11ac84fe4c386b4ff8e75bd
