### ISSUE TITLE
hang when using italics inside of *** block

### ISSUE THREAD

**Issue by vapier** [igorshubovych/markdownlint-cli#99]
the md engine we're using supports `***` as a standoff block.  the lint tool hangs when encountering this.

example md content:
```md
*** note
*NB*: This is only available to blah.
***
```

testing with:
* node-12.14.1
* markdown-0.20.3
* markdownlint-cli-0.23.1

**Comment by DavidAnson** [comment]
Thanks. This is fixed by https://github.com/DavidAnson/markdownlint/commit/26e70a2c6d8b27c7dde5528d004c61b45dc55d1e for the next release of the library.

Note that the (ab)use of `***` like this confuses `MD037/no-space-in-emphasis` to think it's inside a strong/emphasized section. That's not fixable given the current implementation, but the hang should be.

**Comment by vapier** [comment]
yeah, i don't expect full support for the `***` extension here.  i don't have control/choice over the renderer engine :/.

thanks for the quick fix.

**Comment by DavidAnson** [comment]
Fixed in `0.23.2`, just published.
